require "user.options"
require "user.colors"
require "user.keymaps"
require "user.plugins"
require "user.treesitter"
require "user.cmp"
require "user.illuminate"
require "user.toggleterm"
require "user.alpha"
require "user.barbar"
require "user.nvim-tree"
require "user.telescope"
require "user.neoscroll"
require "user.whichkey"
require "user.lsp"

require "user.lualine"
